### ISSUE TITLE
Example of HTML conversion

### ISSUE THREAD

**Issue by mrzv** [adobe/hyde#18]
It would be great to have a standalone example of converting hyde's output into HTML. You have all the necessary bits in [stlab](https://github.com/stlab/stlab.github.io), but it would be very convenient, speaking as a user, to have a stripped down example with just the essential parts (basically, Jenkins templates, if I understand it correctly).

(It would also be nice to have such an example for Hugo, but that's probably too much to ask.)

**Comment by fosterbrereton** [comment]
I'll try to get a sample site building from the test files, and include the necessary Jekyll components in the repo.

**Comment by fosterbrereton** [comment]
I have added a PR for the Jekyll template [here](https://github.com/adobe/hyde/pull/23). Please let me know if it'll suffice.

**Comment by mrzv** [comment]
Looks great. Thanks!

**Comment by fosterbrereton** [comment]
Can you look over the documentation [here](https://github.com/stlab/stlab.github.io/blob/master/README.md) and make sure your Jekyll setup is correct? There are a number of dependencies that I think are GitHub Pages-specific that I think you'll need to install.

**Comment by mrzv** [comment]
I can serve stlab repository locally without any problems. (I did it originally, when I was trying to figure out what output hyde produces.) I just double-checked and it still works. But running the same command for `test_site` (that you have in `serve.sh`) produced the error above.

**Comment by fosterbrereton** [comment]
The only thing I did to create the hyde template was duplicate the stlab one and remove some stlab-specific details. Could you read through [this thread](https://github.com/jekyll/jekyll/issues/4705) to see if one of the solutions presented within might address the problem?

**Comment by fosterbrereton** [comment]
We might need to add `repository: adobe/hyde` to the `_config.yml` file. Can you try that in addition to any other options? (I am not well-versed enough with Jekyll to know why it's working locally over here...)

**Comment by fosterbrereton** [comment]
Another fix for the problem would be to have an `origin` remote defined for the local github repo. Is that the case for you?

**Comment by mrzv** [comment]
I already had `origin` remote defined, but adding `repository: adobe/hyde` to `_config.yml` solved the problem. Thanks!

**Comment by fosterbrereton** [comment]
Fixed with PR #23.
