### ISSUE TITLE
"title" should be scalar, not editable scalar

### ISSUE THREAD

**Issue by lums658** [adobe/hyde#64]
**Describe the bug**
When running Hyde, many classes etc get the name of their enclosing folder as the default "title" field, rather than the actual name of the thing.

Line 885 of yaml_base_emitter should be:
    failure |= check_scalar(filepath, have, expected, "", merged, "title");

Rather than
    failure |= check_editable_scalar(filepath, have, expected, "", merged, "title");

I don't believe title should be an "editable_scalar"

**To Reproduce**
Build and run Hyde on a fresh set of code.  If the code has a file say foo.hpp with a class bar in it, the md file for the bar class will have foo.hpp as the title rather than bar.

**Expected behavior**
The title should be bar.

**Screenshots**
The above change seems to fix the problem

**Desktop (please complete the following information):**
 - OS: ubuntu, clang-9

**Comment by fosterbrereton** [comment]
This issue has been fixed - thanks for the report
